apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: zena07/ticket
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/ticket"
            - name: NATS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLIENT_ID
              value: "bookit"
            - name: NATS_URI
              value: "http://nats-srv:4222"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-srv
spec:
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 4000
      targetPort: 4000
